core/core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="App API",
        default_version="v1",
        description="Brief descriptions about the api",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="bigdeli.ali3@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

# for testing sentry


def trigger_error(request):
    division_by_zero = 1 / 0


urlpatterns = [
    # urls of the admin panel
    path("admin/", admin.site.urls),
    # url inclusion of the app
    path("", include("website.urls")),
    # testing sentry logger
    path("sentry-debug/", trigger_error),
]

# if this is enable instead of seeing the project you will see a page which shows a simple text as you will be launching soon
if settings.COMINGSOON:
    urlpatterns.insert(
        0, re_path(r"^", TemplateView.as_view(template_name="comingsoon.html"))
    )


# serving medias and static files in debug mode
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# showing debugger toolbar when you are using debug mode
if settings.SHOW_DEBUGGER_TOOLBAR:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]


# showing swagger and restframework api authentications
if settings.SHOW_SWAGGER:
    urlpatterns += [
        path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
        path(
            "swagger/api.json",
            schema_view.without_ui(cache_timeout=0),
            name="schema-json",
        ),
        path(
            "swagger/",
            schema_view.with_ui("swagger", cache_timeout=0),
            name="schema-swagger-ui",
        ),
        path(
            "redoc/",
            schema_view.with_ui("redoc", cache_timeout=0),
            name="schema-redoc",
        ),
    ]


# handling error custom pages
handler400 = "core.error_views.error_400"  # bad_request
handler403 = "core.error_views.error_403"  # permission_denied
handler404 = "core.error_views.error_404"  # page_not_found
handler500 = "core.error_views.error_500"  # server_error

core/website/urls.py
from django.urls import path
from . import views

app_name = "website"

urlpatterns = [
    path("", views.UploadView.as_view(), name="upload"),
]

core/website/models.py
from django.db import models

# Create your models here.

class Photo(models.Model):
    file = models.ImageField(upload_to="photos/")

    # def __str__(self):
    #     return self.file.name

core/website/forms.py
from django import forms
from .models import Photo


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['file']

core/website/views.py
from django.shortcuts import render
from django.views.generic import ListView,FormView,CreateView
from .forms import PhotoForm
from .models import Photo
# Create your views here.


class UploadView(CreateView):
    template_name = 'website/index.html'
    form_class = PhotoForm
    success_url = '/'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["gallery"] = Photo.objects.all()
        return context

core/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ali Bigdeli Django 3.2 Template</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    {% block extra_css %}
    {% endblock %}
</head>

<body>
    <header class="p-3 bg-dark text-white">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                        <use xlink:href="#bootstrap"></use>
                    </svg>
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    <li><a href="{% url 'website:upload' %}" class="nav-link px-2 text-warning">Django3.2 Minio Template</a>
                    </li>
                    
                    <li><a href="#uploadtest" class="nav-link px-2 text-white ">Upload Test</a></li>
                    <li><a href="#Author" class="nav-link px-2 text-white">Author</a></li>
                    <li><a href="#Contact" class="nav-link px-2 text-white">Contact</a></li>
                </ul>


            </div>
        </div>
    </header>
    {% block content %}
    {% endblock %}
    <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                    <svg class="bi" width="30" height="24">
                        <use xlink:href="#bootstrap"></use>
                    </svg>
                </a>
                <span class="text-muted">© 2021 AliBigdeli</span>
            </div>

        </footer>
    </div>
    {% include 'messages.html' %}
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
    crossorigin="anonymous"></script>
{% block extra_js %}
{% endblock %}

</html>

core/templates/comingsoon.html
<!doctype html>
<html lang="en" class="h-100">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Coming Soon</title>


    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">



    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/5.1/examples/cover/cover.css" rel="stylesheet">
</head>

<body class="d-flex h-100 text-center text-white bg-dark">

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header class="mb-auto">
        </header>

        <main class="px-3">
            <h1>Coming Soon</h1>
            <p class="lead">There is going to be a cool website here just come back later and check it out. in the mean
                time share your thoughts with us...</p>

        </main>

        <footer class="mt-auto text-white-50">
        </footer>
    </div>



</body>

</html>

core/templates/messages.html
{% if messages %}
{% for message in messages %}
<div class="alert {% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
{% endfor %}
{% endif %}

{% if form.errors %}
<div class="alert alert-error">
    <h4>Please fix the following errors</h4>
    <ul>
        {% for field in form %}
        {% if field.errors %}
        {% for error in field.errors %}
        <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
        {% endfor %}
        {% endif %}
        {% endfor %}
    </ul>
    {% if form.non_field_errors %}
    {{ form.non_field_errors }}
    {% endif %}
</div>
{% endif %}

core/templates/website/index.html
{% extends "base.html" %}
{% block extra_css %}
<style>
    .logo {
        -webkit-filter: grayscale(100%);
        /* Safari 6.0 - 9.0 */
        filter: grayscale(100%);
    }

    .cropped-img {
        width: 300px;
        height: 300px;
        object-fit: cover;
        object-position: 25% 25%;
    }
</style>
{% endblock %}

{% block content %}
<div class="container px-4 py-5" id="uploadtest">
    <h2 class="pb-2 border-bottom">Upload Test</h2>
    <div class="row featurette py-5">

        <div class="col-md-3 order-md-1">
            <form action="." method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="formFile" class="form-label">Minio Upload Form</label>
                    <input class="form-control" name="file" type="file" id="id_file">
                </div>

                <button class="btn btn-dark w-100" type="submit"> Upload</button>
            </form>
        </div>

        <div class="col-md-9 order-md-2">
            <div class="container">
                <div class="row row-cols-3">
                    {% for photo in gallery %}
                    <div class="col p-3">
                        <img class="cropped-img" src="{{photo.file.url}}"  />
                    </div>
                    {% endfor %}
                </div>
            </div>

        </div>

    </div>
</div>

<div class="container px-4 py-5" id="Author">
    <h2 class="pb-2 border-bottom">Author</h2>
    <div class="row featurette py-5">
        <div class="col-md-8 order-md-2">
            <h2 class="featurette-heading">Ali Bigdeli <span class="text-muted">IOT and AI Developer</span>
            </h2>
            <p class="lead">Ali Bigdeli is an IT graduated and with a degree in artificial intelligence and robotics.
                His interest in the world of artificial intelligence and communications in the world of IoT led him to
                combine the two platforms. As the basis of his education, work, and development.</p>

            <p class="lead">His more than 5 years of programming experience and ability in the field of networking and
                communications facilitated his work process and plays a key role in many projects. Python, C ++ / C, and
                Arduino are his specialties in programming.</p>

            <p class="lead">Since 2016, he has founded a team called ICC-ARIA, whose goals are to teach various
                specialties in the
                field of artificial intelligence and the Internet of Things, in which backend and framework designs such
                as Django play an important role. Ideation and conversion of an idea into a product and reverse
                engineering of products are among his potential abilities.</p>
        </div>
        <div class="col-md-4 order-md-1">
            <img src="https://avatars.githubusercontent.com/u/29748439?v=4" width="100%" height="100%" max-width="400px"
                max-height="400px" alt="">

        </div>
    </div>
</div>
<div class="container px-4 py-5" id="Contact">
    <h2 class="pb-2 border-bottom">Contact</h2>
    <div class="row align-items-md-stretch">
        <div class="col-md-6">
            <div class="h-100 p-5">
                <h2>Reach ME</h2>
                <p>you can reach me using other social media platforms such as:</p>
                <ul class="justify-content-start list-unstyled d-flex">
                    <li class="ms-3"><a class="text-muted" href="https://github.com/AliBigdeli" target="_blank">
                            <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" fill="currentColor"
                                class="bi bi-github" viewBox="0 0 16 16">
                                <path
                                    d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z" />
                            </svg>
                        </a></li>
                    <li class="ms-3"><a class="text-muted" href="https://www.linkedin.com/in/thealibigdeli/"
                            target="_blank"><svg xmlns="http://www.w3.org/2000/svg" width="45" height="45"
                                fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                                <path
                                    d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z" />
                            </svg></a></li>

                    <li class="ms-3"><a class="text-muted" href="https://www.youtube.com/in/thealibigdeli/"
                            target="_blank"><svg xmlns="http://www.w3.org/2000/svg" width="45" height="45"
                                fill="currentColor" class="bi bi-youtube" viewBox="0 0 16 16">
                                <path
                                    d="M8.051 1.999h.089c.822.003 4.987.033 6.11.335a2.01 2.01 0 0 1 1.415 1.42c.101.38.172.883.22 1.402l.01.104.022.26.008.104c.065.914.073 1.77.074 1.957v.075c-.001.194-.01 1.108-.082 2.06l-.008.105-.009.104c-.05.572-.124 1.14-.235 1.558a2.007 2.007 0 0 1-1.415 1.42c-1.16.312-5.569.334-6.18.335h-.142c-.309 0-1.587-.006-2.927-.052l-.17-.006-.087-.004-.171-.007-.171-.007c-1.11-.049-2.167-.128-2.654-.26a2.007 2.007 0 0 1-1.415-1.419c-.111-.417-.185-.986-.235-1.558L.09 9.82l-.008-.104A31.4 31.4 0 0 1 0 7.68v-.123c.002-.215.01-.958.064-1.778l.007-.103.003-.052.008-.104.022-.26.01-.104c.048-.519.119-1.023.22-1.402a2.007 2.007 0 0 1 1.415-1.42c.487-.13 1.544-.21 2.654-.26l.17-.007.172-.006.086-.003.171-.007A99.788 99.788 0 0 1 7.858 2h.193zM6.4 5.209v4.818l4.157-2.408L6.4 5.209z" />
                            </svg></a></li>

                </ul>
            </div>
        </div>
        <div class="col-md-6">
            <div class="h-100 p-5">
                <form action="mailto:bigdeli.ali3@gmail.com" method="get" enctype="text/plain">
                    <div class="form-group">
                        <label for="subject">Subject</label>
                        <input id="subject" name="subject" type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label for="textarea">Body</label>
                        <textarea id="textarea" name="textarea" cols="40" rows="5" aria-describedby="textareaHelpBlock"
                            class="form-control"></textarea>
                        <span id="textareaHelpBlock" class="form-text text-muted">share your thoughts</span>
                    </div>

                    <div class="form-group">
                        <button class="btn btn-dark btn-lg" type="submit">Send</button>
                        <button class="btn btn-secondary btn-lg" type="reset" name="reset">Clear Form</button>
                    </div>

                </form>
            </div>
        </div>
    </div>

</div>
{% endblock %}

{% block extra_js %}
{% endblock %}